### PR TITLE
Issue/9/not detecting players wearing salve in mystics

### LINKED ISSUE #9: Checking other players doesn't work
Seen in chambers, plugin was calling out other players for not wearing salve at mystics while they were indeed wearing them.

### PR DESCRIPTION
**Pull request by NickSpaghetti**

### CODE REVIEW

File: src/main/java/com/sac/SalveAmuletCheckerPlugin.java [hunk 1]
```diff
@@ -26,249 +25,224 @@
...
+
+    private TobState currentTobState;
+    private SalveAmuletCheckerPanel panel;
+    private NavigationButton navButton;
+
+    private static final Set<Integer> SALVE_AMULET_IDS = Set.of(
+            ItemID.SALVE_AMULET,
+            ItemID.SALVE_AMULET_E,
+            ItemID.SALVE_AMULETEI,
+            ItemID.SALVE_AMULETI_26763,
```
Comment (TrevorMDev) [inline src/main/java/com/sac/SalveAmuletCheckerPlugin.java:83]: Nice find, it looks like these variants are from soul wars and emir's arena, which could explain why it felt so random.

**Review by TrevorMDev — APPROVED** [review]
I'm far from adept in this plugin but this looks like it should fix it to me. Thanks!
